# Generated by Django 3.1 on 2020-09-05 10:25

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200905_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=phone_field.models.PhoneField(help_text='Contact phone number', max_length=31, null=True),
        ),
    ]
