# Generated by Django 3.1 on 2020-09-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200905_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.IntegerField(max_length=22, null=True, verbose_name='* Телефон'),
        ),
    ]
